# Generated by Django 4.2.7 on 2023-11-27 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtFinderSale', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='id',
        ),
        migrations.AddField(
            model_name='document',
            name='docno',
            field=models.CharField(default=0, max_length=50, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
    ]
