# Generated by Django 4.2.7 on 2023-11-29 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtFinderSale', '0002_remove_document_id_document_docno'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='author',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
