# Generated by Django 4.2.7 on 2023-11-29 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtFinderSale', '0004_alter_document_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='author',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='tags',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
